#!/usr/bin/env ruby
#symlinks the scripts

bin_dir = '/usr/local/bin'
files = `git ls-files`.lines

files = files.to_a.collect {|f| f.strip}
ignore = ['README', 'login.sh', 'logout.sh', 'symlink_scripts']

(files - ignore).each do |f|
  target_path = File.expand_path(File.join(File.dirname(__FILE__), f))
  source_path =  File.join(bin_dir, f)
  puts `ln -ns #{target_path} #{source_path}`
end
