#!/usr/bin/env ruby
#symlinks the scripts

bin_dir = '/usr/local/bin'
files = `git ls-files`.lines

files.each do |f|
  f = f.strip
  target_path = File.join(File.dirname(__FILE__), f)
  source_path =  File.join(bin_dir, f)
  puts `ln -ns #{target_path} #{source_path}`
end
